services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.mysql
    container_name: atividade02-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atividade
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: atividade02-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_ADDRESS: db               # host do MySQL (nome do servi√ßo)
      MYSQL_PORT: "3306"
      MYSQL_DBNAME: atividade         # <- EXATAMENTE o nome que seu main.py pede
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: app123
    ports:
      - "8200:8200"
    restart: on-failure
